// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickNote.Api.Data;

namespace QuickNote.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuickNote.Api.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NotebookId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Console.Writeline(\"Hello World!\");",
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 1, 12, 11, 25, 5, 241, DateTimeKind.Unspecified).AddTicks(6967), new TimeSpan(0, 3, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(2022, 1, 12, 11, 25, 5, 245, DateTimeKind.Unspecified).AddTicks(5727), new TimeSpan(0, 3, 0, 0, 0)),
                            NotebookId = 1,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Content = "console.log('Hello World!');",
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 1, 12, 11, 25, 5, 245, DateTimeKind.Unspecified).AddTicks(8651), new TimeSpan(0, 3, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(2022, 1, 12, 11, 25, 5, 245, DateTimeKind.Unspecified).AddTicks(8671), new TimeSpan(0, 3, 0, 0, 0)),
                            NotebookId = 1,
                            Title = "Javascript"
                        });
                });

            modelBuilder.Entity("QuickNote.Api.Data.Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Notebooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "code"
                        });
                });

            modelBuilder.Entity("QuickNote.Api.Data.Note", b =>
                {
                    b.HasOne("QuickNote.Api.Data.Notebook", "Notebook")
                        .WithMany("Notes")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("QuickNote.Api.Data.Notebook", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
